export const photos = [
    {
      id: 1,
      title: "Golden Hour at the Coast",
      category: "Landscape",
      coverImage: "/placeholder.svg?height=600&width=800",
      images: [
        "/placeholder.svg?height=600&width=800",
        "/placeholder.svg?height=600&width=800",
        "/placeholder.svg?height=600&width=800",
        "/placeholder.svg?height=600&width=800",
        "/placeholder.svg?height=600&width=800",
      ],
      imageCount: 5,
      description: "A breathtaking sunset series captured along the Pacific coastline.",
      date: "June 15, 2023",
      location: "Big Sur, California",
      camera: "Canon EOS R5",
      lens: "RF 24-70mm f/2.8L",
      aperture: "f/8",
      shutterSpeed: "1/125s",
      iso: "100",
      focalLength: "35mm",
      story:
        "I had been planning this shoot for weeks, tracking the sun's position and waiting for perfect weather conditions. After a 2-mile hike down to this secluded beach, I set up my tripod and captured the entire golden hour sequence. The way the golden light painted the cliffs and reflected off the water created a magical atmosphere that evolved throughout the evening. Each frame in this series captures a different moment as the sun descended, from the initial warm glow to the final dramatic silhouettes against the colorful sky.",
      imageDescriptions: [
        "The initial golden glow as the sun begins to set over the Pacific",
        "Waves crashing against the rocks with warm backlighting",
        "The sun touching the horizon, creating a perfect reflection",
        "Dramatic silhouettes as the light fades",
        "The final moments of twilight with deep blue skies",
      ],
    },
    {
      id: 2,
      title: "Urban Nights",
      category: "Urban",
      coverImage: "/placeholder.svg?height=600&width=800",
      images: [
        "/placeholder.svg?height=600&width=800",
        "/placeholder.svg?height=600&width=800",
        "/placeholder.svg?height=600&width=800",
        "/placeholder.svg?height=600&width=800",
        "/placeholder.svg?height=600&width=800",
        "/placeholder.svg?height=600&width=800",
        "/placeholder.svg?height=600&width=800",
      ],
      imageCount: 7,
      description: "The vibrant energy of city life after dark across multiple locations.",
      date: "September 3, 2023",
      location: "New York City, NY",
      camera: "Sony A7IV",
      lens: "24-70mm f/2.8 GM",
      aperture: "f/4",
      shutterSpeed: "15s",
      iso: "200",
      focalLength: "50mm",
      story:
        "This urban photography series captures the electric energy of New York City after sunset. Over the course of three nights, I explored different neighborhoods and vantage points, from the Brooklyn Bridge to rooftop locations in Manhattan. Each image in this collection tells a part of the city's nocturnal story - the rush of traffic, the glow of neon signs, the quiet moments between the chaos, and the human stories unfolding in the urban landscape.",
      imageDescriptions: [
        "Manhattan skyline from Brooklyn Bridge with light trails",
        "Neon reflections in wet streets of Times Square",
        "Quiet moment in a 24-hour diner",
        "Subway platform with motion blur of passing train",
        "Rooftop view of the city grid at night",
        "Street musician performing under streetlights",
        "Early morning commuters in Grand Central",
      ],
    },
    {
      id: 3,
      title: "Mountain Wilderness",
      category: "Nature",
      coverImage: "/placeholder.svg?height=600&width=800",
      images: [
        "/placeholder.svg?height=600&width=800",
        "/placeholder.svg?height=600&width=800",
        "/placeholder.svg?height=600&width=800",
        "/placeholder.svg?height=600&width=800",
        "/placeholder.svg?height=600&width=800",
        "/placeholder.svg?height=600&width=800",
      ],
      imageCount: 6,
      description: "A multi-day trek through pristine mountain wilderness.",
      date: "July 22, 2023",
      location: "Rocky Mountains, Colorado",
      camera: "Nikon Z7 II",
      lens: "NIKKOR Z 14-30mm f/4 S",
      aperture: "f/11",
      shutterSpeed: "1/250s",
      iso: "64",
      focalLength: "20mm",
      story:
        "This series documents a 4-day backpacking expedition through some of Colorado's most remote wilderness areas. Starting before dawn each day, I captured the changing moods of the mountains - from misty valleys at sunrise to dramatic afternoon storms and star-filled nights. Each photograph represents a different aspect of the mountain experience, showcasing both the grandeur and the intimate details of this pristine environment.",
      imageDescriptions: [
        "Pre-dawn mist rising from alpine lakes",
        "Jagged peaks emerging from morning clouds",
        "Wildflower meadows in full summer bloom",
        "Dramatic storm clouds gathering over ridgelines",
        "Crystal clear mountain lake reflecting snow-capped peaks",
        "Star trails over the mountain silhouettes",
      ],
    },
    {
      id: 4,
      title: "Street Stories",
      category: "Street",
      coverImage: "/placeholder.svg?height=600&width=800",
      images: [
        "/placeholder.svg?height=600&width=800",
        "/placeholder.svg?height=600&width=800",
        "/placeholder.svg?height=600&width=800",
        "/placeholder.svg?height=600&width=800",
        "/placeholder.svg?height=600&width=800",
      ],
      imageCount: 5,
      description: "Candid moments and vibrant street art from urban exploration.",
      date: "April 12, 2023",
      location: "Melbourne, Australia",
      camera: "Fujifilm X-T4",
      lens: "XF 23mm f/1.4 R",
      aperture: "f/2.8",
      shutterSpeed: "1/500s",
      iso: "400",
      focalLength: "23mm",
      story:
        "Melbourne's famous laneways provided the perfect backdrop for this street photography series. Over several days, I wandered through the city's hidden alleys and bustling streets, capturing the intersection of urban art, architecture, and human stories. Each image represents a different facet of street life - from the vibrant murals that transform ordinary walls into galleries, to the candid moments of people navigating their daily lives in this creative urban environment.",
      imageDescriptions: [
        "Colorful mural with passing pedestrian creating perfect composition",
        "Coffee culture in a hidden laneway café",
        "Street musician entertaining lunch crowd",
        "Geometric shadows and architectural details",
        "Late afternoon light illuminating street art",
      ],
    },
    {
      id: 5,
      title: "Ocean Power",
      category: "Seascape",
      coverImage: "/placeholder.svg?height=600&width=800",
      images: [
        "/placeholder.svg?height=600&width=800",
        "/placeholder.svg?height=600&width=800",
        "/placeholder.svg?height=600&width=800",
        "/placeholder.svg?height=600&width=800",
      ],
      imageCount: 4,
      description: "The raw power and beauty of ocean waves in various conditions.",
      date: "March 8, 2023",
      location: "Kauai, Hawaii",
      camera: "Canon EOS R5",
      lens: "RF 70-200mm f/2.8L",
      aperture: "f/10",
      shutterSpeed: "1/1000s",
      iso: "100",
      focalLength: "135mm",
      story:
        "This series captures the ocean in different moods and conditions around the Hawaiian island of Kauai. From calm morning reflections to powerful storm swells, each image showcases the dynamic nature of the sea. I spent several days at various coastal locations, studying wave patterns and waiting for the perfect moments when light, water, and motion combined to create these dramatic scenes.",
      imageDescriptions: [
        "Massive wave crashing against volcanic rocks",
        "Gentle morning waves with golden reflections",
        "Storm surge creating dramatic spray patterns",
        "Peaceful tide pools during low tide",
      ],
    },
    {
      id: 6,
      title: "Forest Depths",
      category: "Nature",
      coverImage: "/placeholder.svg?height=600&width=800",
      images: [
        "/placeholder.svg?height=600&width=800",
        "/placeholder.svg?height=600&width=800",
        "/placeholder.svg?height=600&width=800",
        "/placeholder.svg?height=600&width=800",
        "/placeholder.svg?height=600&width=800",
        "/placeholder.svg?height=600&width=800",
      ],
      imageCount: 6,
      description: "An intimate exploration of ancient redwood forests.",
      date: "November 5, 2023",
      location: "Redwood National Park, California",
      camera: "Sony A7R IV",
      lens: "16-35mm f/2.8 GM",
      aperture: "f/5.6",
      shutterSpeed: "1/30s",
      iso: "800",
      focalLength: "16mm",
      story:
        "Walking among these ancient giants is a humbling experience that I wanted to capture from multiple perspectives. This series explores both the grandeur of these massive trees and the intimate details of the forest ecosystem. From the cathedral-like groves to the delicate ferns on the forest floor, each image reveals a different aspect of this primeval landscape that has remained largely unchanged for centuries.",
      imageDescriptions: [
        "Towering redwoods disappearing into morning mist",
        "Intricate patterns of ferns covering the forest floor",
        "Shafts of sunlight filtering through the canopy",
        "Ancient tree trunk showing centuries of growth",
        "Misty forest path winding between giants",
        "Close-up details of bark texture and moss",
      ],
    },
    {
      id: 7,
      title: "Portrait Series",
      category: "Portrait",
      coverImage: "/placeholder.svg?height=600&width=800",
      images: [
        "/placeholder.svg?height=600&width=800",
        "/placeholder.svg?height=600&width=800",
        "/placeholder.svg?height=600&width=800",
        "/placeholder.svg?height=600&width=800",
        "/placeholder.svg?height=600&width=800",
      ],
      imageCount: 5,
      description: "Capturing human emotion and connection in various settings.",
      date: "August 17, 2023",
      location: "Santorini, Greece",
      camera: "Nikon Z6 II",
      lens: "NIKKOR Z 85mm f/1.8 S",
      aperture: "f/2.8",
      shutterSpeed: "1/1000s",
      iso: "100",
      focalLength: "85mm",
      story:
        "This portrait series was created during a workshop in Santorini, focusing on capturing authentic human emotions against the stunning backdrop of the Greek islands. Each portrait tells a different story - from contemplative silhouettes against the famous sunsets to candid moments of joy and connection. The goal was to create images that reveal something essential about each subject while incorporating the unique beauty of the location.",
      imageDescriptions: [
        "Silhouette against the famous Santorini sunset",
        "Candid laughter during golden hour",
        "Contemplative moment overlooking the Aegean Sea",
        "Traditional Greek fisherman at work",
        "Young couple sharing a quiet moment",
      ],
    },
    {
      id: 8,
      title: "Architectural Lines",
      category: "Urban",
      coverImage: "/placeholder.svg?height=600&width=800",
      images: [
        "/placeholder.svg?height=600&width=800",
        "/placeholder.svg?height=600&width=800",
        "/placeholder.svg?height=600&width=800",
        "/placeholder.svg?height=600&width=800",
        "/placeholder.svg?height=600&width=800",
        "/placeholder.svg?height=600&width=800",
      ],
      imageCount: 6,
      description: "Geometric patterns and modern design in contemporary architecture.",
      date: "February 20, 2023",
      location: "Singapore",
      camera: "Canon EOS R6",
      lens: "RF 15-35mm f/2.8L",
      aperture: "f/8",
      shutterSpeed: "1/250s",
      iso: "100",
      focalLength: "15mm",
      story:
        "Singapore's modern architecture provides endless opportunities for geometric photography. This series explores the interplay of lines, shapes, and reflections in the city's most innovative buildings. Shot over several days at different times to capture varying light conditions, each image focuses on the abstract beauty that emerges when architecture is viewed through a photographer's eye.",
      imageDescriptions: [
        "Curved glass facade creating flowing reflections",
        "Geometric patterns in modern office building",
        "Spiral staircase with dramatic lighting",
        "Intersection of multiple building angles",
        "Reflective surfaces creating mirror effects",
        "Minimalist concrete and steel composition",
      ],
    },
    {
      id: 9,
      title: "Wildlife Encounters",
      category: "Nature",
      coverImage: "/placeholder.svg?height=600&width=800",
      images: [
        "/placeholder.svg?height=600&width=800",
        "/placeholder.svg?height=600&width=800",
        "/placeholder.svg?height=600&width=800",
        "/placeholder.svg?height=600&width=800",
        "/placeholder.svg?height=600&width=800",
      ],
      imageCount: 5,
      description: "Intimate moments with wildlife in their natural habitats.",
      date: "October 10, 2023",
      location: "Yellowstone National Park, Wyoming",
      camera: "Sony A1",
      lens: "200-600mm f/5.6-6.3 G",
      aperture: "f/6.3",
      shutterSpeed: "1/1000s",
      iso: "800",
      focalLength: "600mm",
      story:
        "This wildlife series documents several days of patient observation in Yellowstone National Park. Each image represents hours of waiting and watching, studying animal behavior to capture authentic moments of life in the wild. From powerful predators to gentle grazers, this collection showcases the incredible diversity of wildlife that calls Yellowstone home, while emphasizing the importance of conservation and respectful wildlife photography practices.",
      imageDescriptions: [
        "Majestic elk silhouetted against morning mist",
        "Grizzly bear fishing in pristine mountain stream",
        "Bison herd moving across the Lamar Valley",
        "Wolf pack interaction during golden hour",
        "Great blue heron hunting in thermal pools",
      ],
    },
  ]
  
  export const trips = [
    {
      id: 1,
      title: "Tokyo Adventure",
      location: "Tokyo, Japan",
      date: "March 2024",
      duration: "7 days",
      description:
        "Exploring the vibrant streets of Tokyo, from traditional temples to modern skyscrapers. An incredible journey through culture and cuisine.",
      coverImage: "/placeholder.svg?height=600&width=800",
      images: [
        "/placeholder.svg?height=400&width=600",
        "/placeholder.svg?height=400&width=600",
        "/placeholder.svg?height=400&width=600",
        "/placeholder.svg?height=400&width=600",
        "/placeholder.svg?height=400&width=600",
        "/placeholder.svg?height=400&width=600",
      ],
      highlights: [
        "Shibuya Crossing",
        "Mount Fuji",
        "Traditional Temples",
        "Street Food",
        "Shinjuku Nightlife",
        "Meiji Shrine",
      ],
      story:
        "Tokyo is a city of contrasts, where ancient traditions and cutting-edge technology exist side by side. My week-long adventure began in the historic Asakusa district, home to the magnificent Senso-ji Temple. The vibrant atmosphere, with its traditional shops and food stalls, provided a perfect introduction to Japanese culture. From there, I ventured into the modern heart of the city, exploring the neon-lit streets of Shinjuku and Shibuya. The famous Shibuya Crossing, often called the busiest intersection in the world, was a highlight – watching thousands of people cross simultaneously in perfect order was mesmerizing. A day trip to Mount Fuji offered a peaceful contrast to the urban energy. Although clouds obscured the summit, the surrounding lakes and forests were breathtakingly beautiful. Back in Tokyo, I explored the city's incredible food scene, from humble ramen shops to high-end sushi restaurants. Every meal was an adventure in itself, with flavors and presentations that were both familiar and surprising. The efficiency of Tokyo's public transportation system made it easy to explore different neighborhoods, each with its own distinct character. From the trendy boutiques of Harajuku to the electronic wonderland of Akihabara, every district offered new discoveries. As my journey came to an end, I found myself already planning my return to this fascinating city that never stops reinventing itself.",
      transportation: "Subway, JR Lines, and Walking",
      cuisine: "Sushi, Ramen, Tempura, Street Food",
      places: [
        {
          name: "Senso-ji Temple",
          type: "Cultural Site",
          image: "/placeholder.svg?height=400&width=600",
          description:
            "Tokyo's oldest temple, dating back to 645 AD. The approach through Nakamise Shopping Street is lined with traditional shops selling souvenirs and snacks.",
        },
        {
          name: "Shibuya Crossing",
          type: "Urban Landmark",
          image: "/placeholder.svg?height=400&width=600",
          description:
            "The world's busiest pedestrian crossing, where up to 3,000 people cross at once during peak times. The surrounding area is filled with shopping, dining, and entertainment options.",
        },
        {
          name: "Meiji Shrine",
          type: "Spiritual Site",
          image: "/placeholder.svg?height=400&width=600",
          description:
            "A peaceful Shinto shrine dedicated to Emperor Meiji and Empress Shoken, surrounded by a lush forest of 120,000 trees in the heart of Tokyo.",
        },
      ],
      highlightDescriptions: [
        "Experiencing the organized chaos of the world's busiest intersection was surreal.",
        "The majestic mountain appeared from the clouds on our second attempt, a truly magical moment.",
        "Finding moments of peace and reflection amidst the bustling city.",
        "Sampling everything from convenience store onigiri to Michelin-starred ramen.",
      ],
    },
    {
      id: 2,
      title: "European Road Trip",
      location: "France, Italy, Switzerland",
      date: "August 2023",
      duration: "14 days",
      description:
        "A magical road trip through the heart of Europe, discovering charming villages, stunning landscapes, and rich history.",
      coverImage: "/placeholder.svg?height=600&width=800",
      images: [
        "/placeholder.svg?height=400&width=600",
        "/placeholder.svg?height=400&width=600",
        "/placeholder.svg?height=400&width=600",
        "/placeholder.svg?height=400&width=600",
        "/placeholder.svg?height=400&width=600",
        "/placeholder.svg?height=400&width=600",
      ],
      highlights: [
        "Swiss Alps",
        "Tuscany Vineyards",
        "Paris Museums",
        "Italian Cuisine",
        "Alpine Lakes",
        "Medieval Villages",
      ],
      story:
        "Our European adventure began in Paris, where we spent three days exploring the city's iconic landmarks and hidden gems. From the Eiffel Tower to the narrow streets of Montmartre, every corner of the city offered something new to discover. The Louvre alone could have occupied our entire stay, but we managed to tear ourselves away to continue our journey. Driving south through the French countryside, we stopped at charming villages and historic sites before crossing into Italy. Tuscany welcomed us with rolling hills covered in vineyards and olive groves. We stayed in a converted farmhouse with panoramic views of the countryside, waking each morning to misty valleys that gradually revealed their beauty as the sun rose. Days were spent exploring medieval towns like San Gimignano and Siena, while evenings were dedicated to sampling the region's exceptional food and wine. The Italian portion of our trip concluded in the Dolomites, where jagged peaks and alpine meadows created a dramatic landscape unlike anything we had seen before. Hiking trails led us to crystal-clear lakes and panoramic viewpoints that made every step worthwhile. Crossing into Switzerland, we were immediately struck by the pristine villages and impeccable infrastructure. The Swiss Alps provided the perfect finale to our journey, with cable cars whisking us up to snow-capped peaks even in summer. Lake Geneva offered a more relaxed pace, with elegant promenades and refreshing swims. Throughout our two-week adventure, we were constantly amazed by the diversity of landscapes, cultures, and cuisines that Europe offers within relatively short distances. From bustling cities to remote mountain villages, each destination had its own character and charm, leaving us with memories that will last a lifetime.",
      transportation: "Rental Car and Local Trains",
      cuisine: "French Pastries, Italian Pasta, Swiss Chocolate",
      places: [
        {
          name: "Paris",
          type: "City",
          image: "/placeholder.svg?height=400&width=600",
          description:
            "The City of Light captivated us with its blend of history, art, and culinary excellence. Beyond the famous landmarks, we discovered charming neighborhoods and local cafés.",
        },
        {
          name: "Tuscany",
          type: "Region",
          image: "/placeholder.svg?height=400&width=600",
          description:
            "Rolling hills, vineyards, and medieval towns create the iconic Tuscan landscape. We stayed in an agriturismo and enjoyed farm-to-table dining experiences.",
        },
        {
          name: "Swiss Alps",
          type: "Mountain Range",
          image: "/placeholder.svg?height=400&width=600",
          description:
            "Breathtaking mountain scenery with pristine lakes and charming villages. We hiked through alpine meadows and rode scenic mountain railways.",
        },
      ],
    },
    {
      id: 3,
      title: "Iceland Northern Lights",
      location: "Reykjavik, Iceland",
      date: "November 2023",
      duration: "5 days",
      description: "Chasing the Northern Lights across Iceland's dramatic landscapes, from geysers to glaciers.",
      coverImage: "/placeholder.svg?height=600&width=800",
      images: [
        "/placeholder.svg?height=400&width=600",
        "/placeholder.svg?height=400&width=600",
        "/placeholder.svg?height=400&width=600",
        "/placeholder.svg?height=400&width=600",
        "/placeholder.svg?height=400&width=600",
        "/placeholder.svg?height=400&width=600",
      ],
      highlights: ["Northern Lights", "Blue Lagoon", "Geysir", "Glacier Hiking", "Black Sand Beaches", "Waterfalls"],
      story:
        "Iceland had been on my bucket list for years, primarily for the chance to witness the Northern Lights. November offered the perfect combination of dark skies and relatively mild weather for this adventure. After landing in Reykjavik, I spent the first day exploring the compact but charming capital city, with its colorful buildings and innovative architecture. The real journey began when I picked up my rental car and headed out on the famous Ring Road. Iceland's landscape is otherworldly – vast lava fields, towering waterfalls, and geothermal areas where the earth seems alive with bubbling mud pots and erupting geysers. Each day brought new natural wonders, from the powerful Gullfoss waterfall to the black sand beaches of Vik. One of the highlights was hiking on a glacier with an experienced guide, navigating through ice formations that glowed blue in the filtered sunlight. The evenings were dedicated to Northern Lights hunting. For three nights, I waited patiently under clear, cold skies. On the fourth night, my persistence was rewarded when the sky erupted in dancing green lights that gradually expanded to include purples and reds. No photograph can truly capture the experience of standing beneath this natural light show, but the memory is permanently etched in my mind. My journey concluded with a relaxing soak in the Blue Lagoon, where the milky blue geothermal waters provided the perfect contrast to the black lava field surroundings. Iceland's combination of extreme natural beauty and warm, welcoming people made this short trip one of my most memorable adventures.",
      transportation: "Rental Car",
      cuisine: "Fresh Seafood, Traditional Icelandic Lamb, Skyr",
      places: [
        {
          name: "Reykjavik",
          type: "City",
          image: "/placeholder.svg?height=400&width=600",
          description:
            "Iceland's capital combines colorful buildings, innovative architecture, and a vibrant cultural scene. Despite its small size, it offers world-class restaurants and museums.",
        },
        {
          name: "Golden Circle",
          type: "Scenic Route",
          image: "/placeholder.svg?height=400&width=600",
          description:
            "This popular tourist route includes three stunning locations: Þingvellir National Park, the Geysir Geothermal Area, and Gullfoss waterfall.",
        },
        {
          name: "Vatnajökull Glacier",
          type: "Natural Wonder",
          image: "/placeholder.svg?height=400&width=600",
          description:
            "Europe's largest glacier offers incredible ice caves and hiking opportunities. The blue ice formations create an almost alien landscape.",
        },
      ],
    },
  ]
  